ASSET_NAMES: dict[str, list[str]] = {
    "joker": [
        "8 Ball",
        "Abstract Joker",
        "Acrobat",
        "Ancient Joker",
        "Arrowhead",
        "Astronomer",
        "Banner",
        "Baron",
        "Baseball Card",
        "Blackboard",
        "Bloodstone",
        "Blue Joker",
        "Blueprint",
        "Bootstraps",
        "Brainstorm",
        "Bull",
        "Burglar",
        "Burnt Joker",
        "Business Card",
        "Campfire",
        "Canio",
        "Card Sharp",
        "Cartomancer",
        "Castle",
        "Cavendish",
        "Ceremonial Dagger",
        "Certificate",
        "Chaos the Clown",
        "Chicot",
        "Clever Joker",
        "Cloud 9",
        "Constellation",
        "Crafty Joker",
        "Crazy Joker",
        "Credit Card",
        "DNA",
        "Delayed Gratification",
        "Devious Joker",
        "Diet Cola",
        "Driver's License",
        "Droll Joker",
        "Drunkard",
        "Dusk",
        "Egg",
        "Erosion",
        "Even Steven",
        "Faceless Joker",
        "Fibonacci",
        "Flash Card",
        "Flower Pot",
        "Fortune Teller",
        "Four Fingers",
        "Gift Card",
        "Glass Joker",
        "Gluttonous Joker",
        "Golden Joker",
        "Golden Ticket",
        "Greedy Joker",
        "Green Joker",
        "Gros Michel",
        "Hack",
        "Half Joker",
        "Hallucination",
        "Hanging Chad",
        "Hiker",
        "Hit the Road",
        "Hologram",
        "Ice Cream",
        "Invisible Joker",
        "Joker",
        "Joker Stencil",
        "Jolly Joker",
        "Juggler",
        "Loyalty Card",
        "Luchador",
        "Lucky Cat",
        "Lusty Joker",
        "Mad Joker",
        "Madness",
        "Mail-In Rebate",
        "Marble Joker",
        "Matador",
        "Merry Andy",
        "Midas Mask",
        "Mime",
        "Misprint",
        "Mr. Bones",
        "Mystic Summit",
        "Obelisk",
        "Odd Todd",
        "Onyx Agate",
        "Oops! All 6s",
        "Pareidolia",
        "Perkeo",
        "Photograph",
        "Popcorn",
        "Raised Fist",
        "Ramen",
        "Red Card",
        "Reserved Parking",
        "Ride the Bus",
        "Riff-Raff",
        "Rocket",
        "Rough Gem",
        "Runner",
        "Séance",
        "Satellite",
        "Scary Face",
        "Scholar",
        "Seeing Double",
        "Seltzer",
        "Shoot the Moon",
        "Shortcut",
        "Showman",
        "Sixth Sense",
        "Sly Joker",
        "Smeared Joker",
        "Smiley Face",
        "Sock and Buskin",
        "Space Joker",
        "Spare Trousers",
        "Splash",
        "Square Joker",
        "Steel Joker",
        "Stone Joker",
        "Stuntman",
        "Supernova",
        "Superposition",
        "Swashbuckler",
        "The Duo",
        "The Family",
        "The Idol",
        "The Order",
        "The Tribe",
        "The Trio",
        "Throwback",
        "To Do List",
        "To the Moon",
        "Trading Card",
        "Triboulet",
        "Troubadour",
        "Turtle Bean",
        "Vagabond",
        "Vampire",
        "Walkie Talkie",
        "Wee Joker",
        "Wily Joker",
        "Wrathful Joker",
        "Yorick",
        "Zany Joker",
    ],
    "tarot": [
        "Death",
        "Judgement",
        "Justice",
        "Strength",
        "Temperance",
        "The Chariot",
        "The Devil",
        "The Emperor",
        "The Empress",
        "The Fool",
        "The Hanged Man",
        "The Hermit",
        "The Hierophant",
        "The High Priestess",
        "The Lovers",
        "The Magician",
        "The Moon",
        "The Star",
        "The Sun",
        "The Tower",
        "The Wheel of Fortune",
        "The World",
    ],
    "booster": [
        "Arcana Jumbo",
        "Arcana Mega",
        "Arcana Normal",
        "Buffoon Jumbo",
        "Buffoon Mega",
        "Buffoon Normal",
        "Celestial Jumbo",
        "Celestial Mega",
        "Celestial Normal",
        "Spectral Jumbo",
        "Spectral Mega",
        "Spectral Normal",
        "Standard Jumbo",
        "Standard Mega",
        "Standard Normal",
    ],
    "planet": [
        "Ceres",
        "Earth",
        "Eris",
        "Jupiter",
        "Mars",
        "Mercury",
        "Neptune",
        "Planet X",
        "Pluto",
        "Saturn",
        "Uranus",
        "Venus",
    ],
    "spectral": [
        "Ankh",
        "Aura",
        "Black Hole",
        "Cryptid",
        "Deja Vu",
        "Ectoplasm",
        "Familiar",
        "Grim",
        "Hex",
        "Immolate",
        "Incantation",
        "Medium",
        "Ouija",
        "Sigil",
        "Talisman",
        "The Soul",
        "Trance",
        "Wraith",
    ],
    "voucher": [
        "Antimatter",
        "Blank",
        "Clearance Sale",
        "Crystal Ball",
        "Directors Cut",
        "Glow Up",
        "Grabber",
        "Hieroglyph",
        "Hone",
        "Illusion",
        "Liquidation",
        "Magic Trick",
        "Money Tree",
        "Nacho Tong",
        "Observatory",
        "Omen Globe",
        "Overstock",
        "Overstock Plus",
        "Paint Brush",
        "Palette",
        "Petroglyph",
        "Planet Merchant",
        "Planet Tycoon",
        "Recyclomancy",
        "Reroll Glut",
        "Reroll Surplus",
        "Retcon",
        "Seed Money",
        "Tarot Merchant",
        "Tarot Tycoon",
        "Telescope",
        "Wasteful",
    ],
    "sticker": [
        "Eternal",
        "Perishable",
        "Rental",
    ],
    "tag": [
        "Boss Tag",
        "Buffoon Tag",
        "Charm Tag",
        "Coupon Tag",
        "D6 Tag",
        "Double Tag",
        "Economy Tag",
        "Ethereal Tag",
        "Foil Tag",
        "Garbage Tag",
        "Handy Tag",
        "Holographic Tag",
        "Investment Tag",
        "Juggle Tag",
        "Meteor Tag",
        "Negative Tag",
        "Orbital Tag",
        "Polychrome Tag",
        "Rare Tag",
        "Speed Tag",
        "Standard Tag",
        "Top-up Tag",
        "Uncommon Tag",
        "Voucher Tag",
    ],
    "modifier": [
        "Blue Seal",
        "Bonus",
        "Foil",
        "Glass",
        "Gold",
        "Gold Seal",
        "Holographic",
        "Lucky",
        "Mult",
        "Negative",
        "Polychrome",
        "Purple Seal",
        "Red Seal",
        "Steel",
        "Stone",
        "Wild",
    ],
    "stake": [
        "Black Stake",
        "Blue Stake",
        "Gold Stake",
        "Green Stake",
        "Orange Stake",
        "Purple Stake",
        "Red Stake",
        "White Stake",
    ],
    "blind": [
        "Amber Acorn",
        "Big Blind",
        "Cerulean Bell",
        "Crimson Heart",
        "Small Blind",
        "The Arm",
        "The Club",
        "The Eye",
        "The Fish",
        "The Flint",
        "The Goad",
        "The Head",
        "The Hook",
        "The House",
        "The Manacle",
        "The Mark",
        "The Mouth",
        "The Needle",
        "The Ox",
        "The Pillar",
        "The Plant",
        "The Psychic",
        "The Serpent",
        "The Tooth",
        "The Wall",
        "The Water",
        "The Wheel",
        "The Window",
        "Verdant Leaf",
        "Violet Vessel",
    ],
}
